todo/config/routes.rb
Rails.application.routes.draw do
  root to: "task_lists#index"
  resources :task_lists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

todo/app/models/task_list.rb
class TaskList < ApplicationRecord

  acts_as_paranoid

  attribute :status

  # find open tasks
  scope :opened, -> { where(completed_at: nil) }
  # find completed tasks
  scope :closed, -> { where.not(completed_at: nil) }

  # Mark task with "completed" status
  def close
    self.completed_at = Time.now
  end

  # Check task for "completed" status
  def close?
    !completed_at.nil?
  end

  # Mark task with "completed" status with save
  def close!
    close; save
  end

  # Mark task with "open" status
  def open
    self.completed_at = nil
  end

  # Check task for "open" status
  def open?
    completed_at.nil?
  end

  # Mark task with "open" status with save
  def open!
    open; save
  end

  # Get current status
  # Temporaly method. Maybe this will be released with enum
  def status
    open? ? I18n.t('open') : I18n.t('close')
  end

  # Get current status
    def status=(new_status)
    case new_status
    when 'open'
      open
    when 'close'
      close
    end
  end
end

todo/app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController

  before_action :set_task_list, only: %i[ show edit update destroy ]

  # GET /task_lists or /task_lists.json
  def index
    @task_lists = TaskList.all
  end

  # GET /task_lists/1 or /task_lists/1.json
  def show
  end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new
  end

  # GET /task_lists/1/edit
  def edit
  end

  # POST /task_lists or /task_lists.json
  def create
    @task_list = TaskList.new(task_list_params)

    respond_to do |format|
      if @task_list.save
        format.html { redirect_to @task_list, notice: "Task list was successfully created." }
        format.json { render :show, status: :created, location: @task_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_lists/1 or /task_lists/1.json
  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        format.html { redirect_to @task_list, notice: "Task list was successfully updated." }
        format.json { render :show, status: :ok, location: @task_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1 or /task_lists/1.json
  def destroy
    @task_list.destroy
    respond_to do |format|
      format.html { redirect_to task_lists_url, notice: "Task list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_list_params
      params.require(:task_list).permit(:title, :description, :status)
    end
end

todo/app/helpers/task_lists_helper.rb
module TaskListsHelper
end

todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsyncTodo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

todo/app/views/task_lists/_form.html.erb
<%= form_with(model: task_list) do |form| %>
  <% if task_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
        <% task_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, t('activerecord.attributes.task_list.statuses').map{|k, v| [v,k]} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

todo/app/views/task_lists/edit.html.erb
<h1>Editing Task List</h1>

<%= render 'form', task_list: @task_list %>

<%= link_to 'Show', @task_list %> |
<%= link_to 'Back', task_lists_path %>

todo/app/views/task_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Lists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_lists.each do |task_list| %>
      <tr>
        <td><%= task_list.title %></td>
        <td><%= task_list.description %></td>
        <td><%= task_list.status %></td>
        <td><%= link_to 'Show', task_list %></td>
        <td><%= link_to 'Edit', edit_task_list_path(task_list) %></td>
        <td><%= link_to 'Destroy', task_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task List', new_task_list_path %>

todo/app/views/task_lists/new.html.erb
<h1>New Task List</h1>

<%= render 'form', task_list: @task_list %>

<%= link_to 'Back', task_lists_path %>

todo/app/views/task_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task_list.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task_list.status %>
</p>


<%= link_to 'Edit', edit_task_list_path(@task_list) %> |
<%= link_to 'Back', task_lists_path %>